api/urls.py
from django.urls import path
from . import views
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
)

urlpatterns = [
    path("users/token/", TokenObtainPairView.as_view(), name="token_obtain_pair"),
    path("users/token/refresh/", TokenRefreshView.as_view(), name="token_refresh"),
    path("", views.getRoutes),
    path("projects/", views.getProjects),
    path("projects/<str:pk>", views.getProject),
    path("projects/<str:pk>/vote/", views.projectVote),
    path("remove-tag/", views.removeTag),
]

devsearch/urls.py
from re import template
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('projects/', include('projects.urls')),
    path('', include('users.urls')),
    path('api/', include('api.urls')),
    path('reset_password', auth_views.PasswordResetView.as_view(template_name="reset_password.html"), name='reset_password'),
    path('reset_password_sent', auth_views.PasswordResetDoneView.as_view(template_name="reset_password_sent.html"), name='password_reset_done'),
    path('reset/<uidb64>/<token>', auth_views.PasswordResetConfirmView.as_view(template_name="reset.html"), name='password_reset_confirm'),
    path('reset/done', auth_views.PasswordResetCompleteView.as_view(template_name="reset_password_complete.html"), name='password_reset_complete'),
]
 
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from unicodedata import name
from django.urls import path
from . import views

urlpatterns = [
    path('login/', views.loginUser, name="login"),
    path('logout/', views.logoutUser, name="logout"),    
    path('register/', views.registerUser, name="register"),    
    path('', views.profiles, name="profiles"),
    path('profile/<str:pk>', views.userProfile, name="user-profile"),
    path('account/', views.userAccount, name="account"),
    path('edit-account/', views.editAccount, name="edit-account"),
    path('create-skill/', views.createSkill, name="create-skill"),
    path('update-skill/<str:pk>', views.updateSkill, name="update-skill"),
    path('delete-skill/<str:pk>', views.deleteSKill, name="delete-skill"),
    path('inbox/', views.inbox, name="inbox"),
    path('inbox/<str:pk>', views.viewMessage, name="message"),
    path('create-message/<str:pk>', views.createMessage, name="create-message"),
]

projects/models.py
from datetime import datetime
from django.db import models
from users.models import Profile
import uuid


# Create your models here.
class Project(models.Model):
    owner= models.ForeignKey(Profile, null=True, blank=True, on_delete=models.CASCADE)
    title=  models.CharField(max_length=100)
    description = models.TextField(null=True, blank=True)
    feature_image = models.ImageField(default='default.jpg', null=True, blank=True)
    demo_link = models.CharField(max_length=2000, null = True, blank=True)
    source_link = models.CharField(max_length=2000, null=True, blank=True)
    tags = models.ManyToManyField('Tag', blank=True)
    vote_total = models.IntegerField(default=0, null=True, blank=True)
    vote_ratio = models.IntegerField(default=0, null=True, blank=True)
    created = models.DateTimeField(auto_now_add=True)
    id = models.UUIDField(default=uuid.uuid4, unique=True, primary_key=True, editable=False)

    def __str__(self):
        return self.title

    class Meta:
        ordering = ['-vote_ratio', '-vote_total', 'title']

    @property
    def imageURL(self):
        try:
            url = self.feature_image.url
        except:
            url = ''
        return url

    @property
    def reviewers(self):
        queryset = self.review_set.all().values_list('owner__id', flat=True)
        return queryset
    
    @property
    def getVoteCount(self):
        reviews = self.review_set.all()
        upVotes = reviews.filter(value = 'up').count()
        totalVotes = reviews.count()

        ratio = (upVotes / totalVotes) * 100
        self.vote_total = totalVotes
        self.vote_ratio = ratio
        self.save()

class Review(models.Model):
    VOTE_TYPE = (
        ('up', 'Up Vote'),
        ('down', 'Down Vote'),
    )
    owner = models.ForeignKey(Profile, on_delete=models.CASCADE, null=True)
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    body = models.TextField(null=True, blank=True)
    value = models.CharField(max_length=200, choices=VOTE_TYPE)
    created = models.DateTimeField(auto_now_add=True)
    id = models.UUIDField(default=uuid.uuid4, unique=True, primary_key=True, editable=False)

    class Meta:
        unique_together= [['owner', 'project']]

    def __str__(self):
        return self.value
    
class Tag(models.Model):
    name = models.CharField(max_length=200)
    created = models.DateTimeField(auto_now_add=True)
    id = models.UUIDField(default=uuid.uuid4, unique=True, primary_key=True, editable=False)

    def __str__(self):
        return self.name

users/models.py
from distutils.command.upload import upload
from email.policy import default
from unicodedata import name
from django.db import models
from django.contrib.auth.models import User
import uuid



class Profile(models.Model):

    user = models.OneToOneField(User, on_delete= models.CASCADE, null=True, blank=True)
    name = models.CharField(max_length=200, blank=True, null=True)
    email= models.EmailField(max_length=200, blank=True, null=True)
    username = models.CharField(max_length=200, blank=True, null=True)
    location = models.CharField(max_length=200, blank=True, null=True)
    short_intro = models.CharField(max_length=200, blank=True, null=True)
    bio = models.TextField(blank=True, null=True)
    profile_image = models.ImageField(null=True, blank=True, upload_to ="profile/", default="profile/user-default.png")
    social_github = models.CharField(max_length=200, blank=True, null=True)
    social_twitter = models.CharField(max_length=200, blank=True, null=True)
    social_linkedin = models.CharField(max_length=200, blank=True, null=True)
    social_youtube = models.CharField(max_length=200, blank=True, null=True)
    social_website = models.CharField(max_length=200, blank=True, null=True)
    created = models.DateTimeField(auto_now_add=True)
    id = models.UUIDField(default=uuid.uuid4, unique=True, primary_key=True, editable=False)

    def __str__(self):
        return str(self.username)
    class Meta:
        ordering= ['created']
    
    @property
    def imageURL(self):
        try:
            url = self.profile_image.url
        except:
            url = ''
        return url
        

class Skill(models.Model):
    owner = models.ForeignKey(Profile, on_delete=models.CASCADE, null=True, blank=True)
    name = models.CharField(max_length=200, blank=True, null=True)
    description = models.TextField(null=True, blank=True)
    created = models.DateTimeField(auto_now_add=True)
    id= models.UUIDField(default=uuid.uuid4, unique=True, primary_key=True, editable=False)

    def __str__(self):
        return str(self.name)

class Message(models.Model):
    sender = models.ForeignKey(Profile, on_delete=models.SET_NULL, null=True, blank=True)
    recipient = models.ForeignKey(Profile, on_delete=models.SET_NULL, null=True, blank=True, related_name="messages")
    name = models.CharField(max_length=100, null=True, blank=True)
    email = models.EmailField(max_length=100, null=True, blank=True)
    subject = models.CharField(max_length=100, null=True, blank=True)
    body = models.TextField()
    is_read = models.BooleanField(default=False, null=True)
    created = models.DateTimeField(auto_now_add=True)
    id= models.UUIDField(default=uuid.uuid4, unique=True, primary_key=True, editable=False)

    def __str__(self):
        return self.subject
    class Meta:
        ordering = ['is_read', '-created']

    

users/forms.py
from dataclasses import fields
from pyexpat import model
from statistics import mode
from django.forms import ModelForm, widgets
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from.models import Profile, Skill, Message

class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model= User
        fields = ['first_name', 'email', 'username', 'password1', 'password2']

        labels = {
            'first_name': 'Name',
        }
    
    def __init__(self, *args, **kwargs):
        super(CustomUserCreationForm, self).__init__(*args, **kwargs)

        for name, field in self.fields.items():
            field.widget.attrs.update({'class': 'input'})

class ProfileForm(ModelForm):

    class Meta:
        model = Profile
        fields= [
            'name',
            'email',
            'username',
            'location',
            'short_intro',
            'bio',
            'profile_image',
            'social_github',
            'social_twitter',
            'social_linkedin',
            'social_youtube',
            'social_website',

        ]
    def __init__(self, *args, **kwargs):
        super(ProfileForm, self).__init__(*args, **kwargs)

        for name, field in self.fields.items():
            field.widget.attrs.update({'class': 'input'})

class SkillForm(ModelForm):
    class Meta:
        model = Skill
        fields= '__all__'
        exclude = ['owner']
    def __init__(self, *args, **kwargs):
        super(SkillForm, self).__init__(*args, **kwargs)

        for name, field in self.fields.items():
            field.widget.attrs.update({'class': 'input'})

class MessageForm(ModelForm):
    class Meta:
        model = Message
        fields = ['name', 'email', 'subject', 'body']
        
    def __init__(self, *args, **kwargs):
        super(MessageForm, self).__init__(*args, **kwargs)

        for name, field in self.fields.items():
            field.widget.attrs.update({'class': 'input'})

users/views.py
from atexit import register
from email import message
import imp
from multiprocessing import context

from django.shortcuts import get_object_or_404, render,redirect
from django.contrib.auth import login, authenticate, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.contrib import messages
from .models import Profile, Message
from .utils import searchProfiles, paginateProfiles
from .forms import CustomUserCreationForm, ProfileForm, SkillForm, MessageForm

def loginUser(request):

    page = 'login'

    context={
        'page':page
    }

    if request.user.is_authenticated:
        return redirect('profiles')

    if request.method == "POST":
        username = request.POST['username'].lower()
        password = request.POST['password']

        try:
            user = User.objects.get(username = username)
        except:
            messages.error(request, 'Username does not exist')

        user = authenticate(request, username=username, password=password)

        if user is not None:
            login(request, user)
            messages.success(request, 'User logged in!')
            return redirect(request.GET['next'] if 'next' in request.GET else 'account')
        
        else:
            messages.error(request, 'Username or password is incorrect')

    return render(request, 'users/login_register.html', context)

def logoutUser(request):
    logout(request)
    messages.info(request, 'User was logged out!')
    return redirect('login')

def registerUser(request):
    page = 'register'
    form = CustomUserCreationForm()

    if request.method == 'POST':
        form=CustomUserCreationForm(request.POST)

        if form.is_valid():
            user = form.save(commit=False)
            user.username = user.username.lower()
            user.save()

            messages.success(request, "User account was created!")
            login(request, user)
            return redirect('edit-account')

        else:
            messages.error(request, "An error has occured during registration")

    context={
        'page':page,
        'form':form,
    }

    return render(request, 'users/login_register.html', context)


def profiles(request):
    
    profiles, search_query = searchProfiles(request)
    custom_range, profiles = paginateProfiles(request, profiles, 3)

    context = {
        'profiles': profiles,
        'search_query': search_query,
        'custom_range': custom_range
    }
    return render(request, 'users/profiles.html', context)


def userProfile(request, pk):
    profile = Profile.objects.get(id=pk)

    topSkills = profile.skill_set.exclude(description__exact="")
    otherSkills = profile.skill_set.filter(description="")

    context ={
        'profile':profile,
        'topSkills':topSkills,
        'otherSkills':otherSkills,
    }
    return render(request, 'users/user-profile.html', context)

@login_required(login_url='login')
def userAccount(request):

    profile = request.user.profile
    skills = profile.skill_set.all()

    context = {
        'profile': profile,
        'skills':skills,
    }

    return render(request, 'users/account.html', context)


@login_required(login_url='login')
def editAccount(request):
    profile = request.user.profile
    form = ProfileForm(instance=profile)
    if request.method== 'POST':
        form = ProfileForm(request.POST, request.FILES, instance=profile)
        if form.is_valid():
            form.save()

            return redirect('account')

    context={
        'form': form,
    }
    return render(request, 'users/profile_form.html', context)

@login_required(login_url='login')
def createSkill(request):
    profile = request.user.profile
    form = SkillForm()
    if request.method == 'POST':
        form= SkillForm(request.POST)
        if form.is_valid():
            skill = form.save(commit=False)
            skill.owner = profile
            skill.save()
            messages.success(request, "Skill was added successfully!")
            return redirect('account')
            
    context={
        'form': form
    }
    
    return render (request, 'users/skill_form.html', context)

@login_required(login_url='login')
def updateSkill(request, pk):
    profile = request.user.profile
    skill = profile.skill_set.get(id=pk)
    form = SkillForm(instance = skill)
    if request.method == 'POST':
        form= SkillForm(request.POST, instance = skill)
        if form.is_valid():
            form.save()
            messages.success(request, "skill was updated!")
            return redirect('account')
            
    context={
        'form': form
    }
    
    return render (request, 'users/skill_form.html', context)

@login_required(login_url='login')
def deleteSKill(request, pk):
    profile = request.user.profile
    skill = profile.skill_set.get(id=pk)
    if request.method == 'POST':
        skill.delete()
        messages.success(request, "skill was deleted!")
        return redirect('account')
       
    context={
        'object': skill
    }
    return render(request, 'delete_template.html', context)

@login_required(login_url='login')
def inbox(request):
    profile = request.user.profile
    messageRequests = profile.messages.all()
    unreadCount = messageRequests.filter(is_read=False).count()

    context={
        'messageRequests': messageRequests,
        'unreadCount': unreadCount,
    }
    return render(request, 'users/inbox.html', context)

@login_required(login_url='login')
def viewMessage(request, pk):
    profile = request.user.profile    
    message = profile.messages.get(id=pk)
    if message.is_read == False:
        message.is_read = True
        message.save()
    context={
        'message':message,
    }
    return render(request, 'users/message.html', context)

def createMessage(request, pk):
    recipient = Profile.objects.get(id=pk)
    form = MessageForm()

    try:
        sender = request.user.profile
    except:
        sender = None
    
    if request.method == 'POST':
        form = MessageForm(request.POST)

        if form.is_valid():
            message = form.save(commit= False)
            message.sender = sender
            message.recipient = recipient
            message.body = message.body.capitalize()

            if sender:
                message.name = sender.name
                message.email = sender.email    
            
            message.save()
            messages.success(request, 'Your message was successfully sent!')
            return redirect('user-profile', pk=recipient.id)
    context={
        'recipient':recipient,
        'form':form
    }
    return render(request, 'users/message_form.html', context)

templates/users/account.html
{% extends 'base.html'  %}

{% block content %}
    <!-- Main Section -->
<!-- Main Section -->
<main class="settingsPage profile my-md">
  <div class="container">
    <div class="layout">
      <div class="column column--1of3">
        <div class="card text-center">
          <div class="card__body dev">
            <a class="tag tag--pill tag--main settings__btn" href="{% url 'edit-account' %}"><i class="im im-edit"></i> Edit</a>
            <img class="avatar avatar--xl dev__avatar" src="{{profile.imageURL}}"  alt="image"/>
            <h2 class="dev__name">{{profile.name}}</h2>
            <p class="dev__title">{{profile.short_intro}}</p>
            <p class="dev__location">Based in {{profile.location}}</p>
            <ul class="dev__social">
              {% if profile.social_github %}
              <li>
                <a
                  title="Github"
                  href="{{profile.social_github}}"
                  target="_blank"
                  ><i class="im im-github"></i
                ></a>
              </li>
              {% endif %} {% if profile.social_twitter %}
              <li>
                <a
                  title="Twitter"
                  href="{{profile.social_twitter}}"
                  target="_blank"
                  ><i class="im im-twitter"></i
                ></a>
              </li>
              {% endif %} {% if profile.social_linkedin %}
              <li>
                <a
                  title="LinkedIn"
                  href="{{profile.social_linkedin}}"
                  target="_blank"
                  ><i class="im im-linkedin"></i
                ></a>
              </li>
              {% endif %} {% if profile.social_youtube %}
              <li>
                <a
                  title="Personal Website"
                  href="{{profile.social_youtube}}"
                  target="_blank"
                  ><i class="im im-youtube"></i
                ></a>
              </li>
              {% endif %} {% if profile.social_website %}
              <li>
                <a
                  title="Personal Website"
                  href="{{profile.social_website}}"
                  target="_blank"
                  ><i class="im im-globe"></i
                ></a>
              </li>
              {% endif %}
            </ul>
            
            <!-- {% if request.user.profile.id != profile.id %}
            <a href="#" class="btn btn--sub btn--lg">Send Message </a>
            {% endif %} -->
              
            
          </div>
        </div>
      </div>
      <div class="column column--2of3">
        <div class="devInfo">
          <h3 class="devInfo__title">About Me</h3>
          <p class="devInfo__about">
            {{profile.bio}}
          </p>
        </div>
        <div class="settings">
          <h3 class="settings__title">Skills</h3>
          <a class="tag tag--pill tag--sub settings__btn tag--lg" href="{% url 'create-skill' %}"><i class="im im-plus"></i> Add Skill</a>
        </div>

        <table class="settings__table">
          
          {% for skill in skills %}
            <tr>
              <td class="settings__tableInfo">
                <h4>{{skill.name}}</h4>
                <p>
                  {{skill.description}}
                </p>
              </td>
              <td class="settings__tableActions">
                <a class="tag tag--pill tag--main settings__btn" href="{% url 'update-skill' skill.id %}"><i class="im im-edit"></i> Edit</a>
                <a class="tag tag--pill tag--main settings__btn" href="{% url 'delete-skill' skill.id %}?next=/account"><i class="im im-x-mark-circle-o"></i>
                  Delete</a>
              </td>
            </tr>
          {% endfor %}
            
        </table>

        <div class="settings">
          <h3 class="settings__title">Projects</h3>
          <a class="tag tag--pill tag--sub settings__btn tag--lg" href="{% url 'create-project' %}"><i class="im im-plus"></i> Add Project</a>
        </div>

        <table class="settings__table">
          
          {% for project in profile.project_set.all %}
            <tr>
              <td class="settings__thumbnail">
                <a href="{% url 'project' project.id  %}"><img src="{{project.imageURL}}" alt="Project Thumbnail" /></a>
              </td>
              <td class="settings__tableInfo">
                <a href="{% url 'project' project.id  %}">{{project.title}}</a>
                <p>
                  {{project.description}}
                </p> 
              </td>
              <td class="settings__tableActions">
                <a class="tag tag--pill tag--main settings__btn" href="{% url 'update-project' project.id %}"><i class="im im-edit"></i> Edit</a>
                <a class="tag tag--pill tag--main settings__btn" href="{% url 'delete-project' project.id %}?next=/account"><i class="im im-x-mark-circle-o"></i>
                  Delete</a>
              </td>
            </tr>
          {% endfor %}
        </table>
      </div>
    </div>
  </div>
</main>


{% endblock %}
    

templates/users/inbox.html
{% extends 'base.html' %}

{% block content %}
<main class="inbox my-xl">
    <div class="content-box">
      <h3 class="inbox__title">New Messages(<span>{{unreadCount}}</span>)</h3>
      <ul class="messages">
          
        {% for message in messageRequests %}
        {% if message.is_read == False %}
        <li class="message message--unread">
          {% else %}
        <li class="message">
          {% endif %}
  
          <a href="{% url 'message' message.id %}">
            <span class="message__author">{{message.name}}</span>
            <span class="message__subject">{{message.subject}}</span>
            <span class="message__date">{{message.created}}</span>
          </a>
        </li>
        {% endfor %}
      </ul>
    </div>
  </main>
{% endblock %}
    

templates/users/login_register.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

    
    {% if page == 'register' %}
        <div class="auth">
            <div class="card">
              <div class="auth__header text-center">
                <a href="/">
                  <img src="{% static 'images/icon.svg' %}" alt="icon" />
                </a>
                <h3>Register an Account</h3>
                <p>Create a new developer account</p>
              </div>
      
              <form action="{% url 'register' %}" method="post" class="form auth__form">
                  {% csrf_token %}
                  
                  {% for field in form %}
                  <div class="form__field">
                    <label for="formInput#text">{{field.label}}</label>
                    {{field}}

                    
                    <!-- {% if field.help_text %}
                      <small>{{field.help_text}}</small>
                    {% endif %} -->
                      
                    {% for error in field.errors %}
                        <p style="color: red;"> {{error}} </p>
                     {% endfor %}
                        
                  </div>
                  {% endfor %}
                <div class="auth__actions">
                  <input class="btn btn--sub btn--lg" type="submit" value="Sign Up" />
                </div>
              </form>
              <div class="auth__alternative">
                <p>Already have an Account?</p>
                <a href="{% url 'login' %}">Log In</a>
              </div>
            </div>
          </div>
    {% else %}
        <div class="auth">
            <div class="card">
            <div class="auth__header text-center">
                <a href="/">
                <img src="{% static 'images/icon.svg'   %}" alt="icon" />
                </a>
                <h3>Account Login</h3>
                <p>Hello Developer, Welcome Back!</p>
            </div>
    
            <form action="" method="post" class="form auth__form">
                {% csrf_token %}
                <!-- Input:Email -->
                <div class="form__field">
                <label for="formInput#text">Username: </label>
                <input
                    class="input input--text"
                    id="formInput#text"
                    type="text"
                    name="username"
                    placeholder="Enter your username..."
                />
                </div>
    
                <!-- Input:Password -->
                <div class="form__field">
                <label for="formInput#password">Password: </label>
                <input
                    class="input input--password"
                    id="formInput#passowrd"
                    type="password"
                    name="password"
                    placeholder="••••••••"
                />
                </div>
                <div class="auth__actions">
                <input class="btn btn--sub btn--lg" type="submit" value="Log In" />
                <a href="{% url 'reset_password' %}">Forget Password?</a>
                </div>
            </form>
            <div class="auth__alternative">
                <p>Don’t have an Account?</p>
                <a href="{% url 'register' %}">Sign Up</a>
            </div>
            </div>
        </div>
    {% endif %}
        
    
{% endblock %}
    

templates/users/user-profile.html
{% extends 'base.html' %} {% block content %}

<!-- Main Section -->
<main class="profile my-md">
  <div class="container">
    <div class="layout">
      <div class="column column--1of3">
        <div class="card text-center">
          <div class="card__body dev">
            <img
              class="avatar avatar--xl"
              src="{{profile.imageURL}}"
            />
            <h2 class="dev__name">{{profile.name}}</h2>
            <p class="dev__title">{{profile.short_intro}}</p>
            <p class="dev__location">Based in {{profile.location}}</p>
            <ul class="dev__social">
              {% if profile.social_github %}
              <li>
                <a
                  title="Github"
                  href="{{profile.social_github}}"
                  target="_blank"
                  ><i class="im im-github"></i
                ></a>
              </li>
              {% endif %} {% if profile.social_twitter %}
              <li>
                <a
                  title="Twitter"
                  href="{{profile.social_twitter}}"
                  target="_blank"
                  ><i class="im im-twitter"></i
                ></a>
              </li>
              {% endif %} {% if profile.social_linkedin %}
              <li>
                <a
                  title="LinkedIn"
                  href="{{profile.social_linkedin}}"
                  target="_blank"
                  ><i class="im im-linkedin"></i
                ></a>
              </li>
              {% endif %} {% if profile.social_youtube %}
              <li>
                <a
                  title="Personal Website"
                  href="{{profile.social_youtube}}"
                  target="_blank"
                  ><i class="im im-youtube"></i
                ></a>
              </li>
              {% endif %} {% if profile.social_website %}
              <li>
                <a
                  title="Personal Website"
                  href="{{profile.social_website}}"
                  target="_blank"
                  ><i class="im im-globe"></i
                ></a>
              </li>
              {% endif %}
            </ul>
            
            {% if request.user.profile.id != profile.id %}
              <a href="{% url 'create-message' profile.id %}" class="btn btn--sub btn--lg">Send Message</a>         
            
              {% endif %}
              
          </div>
        </div>
      </div>
      <div class="column column--2of3">
        <div class="devInfo">
          <h3 class="devInfo__title">About Me</h3>
          <p class="devInfo__about">{{profile.bio}}</p>
        </div>
        <div class="devInfo">
          <h3 class="devInfo__title">Skills</h3>
          <div class="devInfo__skills">
            {% for skill in topSkills %}
                <div class="devSkill">
                <h4 class="devSkill__title">{{skill.name}}</h4>
                <p class="devSkill__info">{{skill.description}}</p>
                </div>
            {% endfor %}

            <h3 class="devInfo__subtitle">Other Skills</h3>
            <div class="devInfo__otherSkills">
                
                {% for skill in otherSkills %}
                <span class="tag tag--pill tag--sub tag--lg">
                    <small>{{skill}}</small>
                  </span>
                {% endfor %}
            </div>
          </div>
        </div>
        <div class="devInfo">
          <h3 class="devInfo__title">Projects</h3>
          <div class="grid grid--two">
              
              {% for project in profile.project_set.all %}
              <div class="column">
                <div class="card project">
                  <a href="{% url 'project' project.id  %}" class="project">
                    <img
                      class="project__thumbnail"
                      src="{{project.imageURL}}"
                      alt="project thumbnail"
                    />
                    <div class="card__body">
                      <h3 class="project__title">{{project.title}}</h3>
                      <p>
                        <a class="project__author" href="{% url 'user-profile' project.owner.id %}"
                          >By {{project.owner.name}}</a
                        >
                      </p>
                      <p class="project--rating">
                        <span style="font-weight: bold">{{project.vote_ratio}}% </span> Postitive
                        Feedback ({{project.vote_total}} Vote{{project.vote_total|pluralize:"s"}})
                        </p>
                      <div class="project__tags">
                          
                          {% for tag in project.tags.all %}
                          <span class="tag tag--pill tag--main">
                            <small>{{tag}}</small>
                          </span>
                          {% endfor %}
                      </div>
                    </div>
                  </a>
                </div>
              </div>
              {% endfor %}
                  
            

            
          </div>
        </div>
      </div>
    </div>
  </div>
</main>
{% endblock %}